---
name: Checks  # name of github actions

on: [push]     # run on push

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub   # logs to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout  # checkout
        uses: actions/checkout@v2
      - name: Test     # run test using docker compose
        run: docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
      - name: Lint   # run linting using docker compose
        run: docker-compose run --rm app sh -c "flake8"